### ISSUE TITLE
Hydrogen bonds from individual frames

### ISSUE THREAD

**Issue by RasmusFonseca** [ELELAB/pyinteraph#1]
Is there a way to make pyinteraph report hydrogen bonds in individual frames instead of just the frequency over the entire simulation?

**Comment by mtiberti** [comment]
No - unfortunately there's no way to do that in PyInteraph at the moment

**Comment by elenapapaleo** [comment]
well perhaps a solution would be  to collect the snapshopts of the traj. in separate pdb files and then to write a wrapper script that use the hydrogen bond function for each of them

**Comment by RasmusFonseca** [comment]
Great, Ill do that for benchmarking. Thanks .. and hope you guys are well back in CPH 😄
