### ISSUE TITLE
I am having this error every time I run tutorial files/

### ISSUE THREAD

**Issue by Ash1000** [ELELAB/pyinteraph#3]
`pyinteraph -s $top -t $traj -r $ref -b --sb-graph sb-graph.dat`

`WARNING:root:PYINTERAPH system variable should contain the path to the PYINTERAPH installation directory! Defaulting to local dir
Traceback (most recent call last):
  File "/usr/local/pyinteraph/pyinteraph", line 166, in <module>
    masses_files = os.listdir(masses_dir)
OSError: [Errno 2] No such file or directory: './/ff_masses'`

**Comment by elenapapaleo** [comment]
you need to provide the path to where pyinteraph is installed or define a system variable for it. 
for example 
export PYINTERAPH=/usr/local/envs/pyinteraph/pyinteraph/
export PATH=$PATH:$PYINTERAPH

where the absolute path need to be replace on the path to where pyinteraph is on your computer
