### ISSUE TITLE
problem with pyinteraph

### ISSUE THREAD

**Issue by degapifa** [ELELAB/pyinteraph#4]
after the installation, when i start tutorial.sh
I have this problem:
Traceback (most recent call last):
  File "/usr/local/pyinteraph//pyinteraph", line 162, in <module>
    from libinteract import libinteract as li
  File "/usr/local/lib/python2.7/dist-packages/libinteract/libinteract.py", line 1, in <module>
    import MDAnalysis as mda
ImportError: No module named MDAnalysis
but, i have MDAnalysis installed.

**Comment by mtiberti** [comment]
Hi,
that depends on how MDAnalysis is available on your system - can you give me some details on your Python installation and what changes you made in the tutorial script file? What do you get if you run `python -c 'import MDAnalysis'`

**Comment by degapifa** [comment]
> Hi,
> that depends on how MDAnalysis is available on your system - can you give me some details on your Python installation and what changes you made in the tutorial script file? What do you get if you run `python -c 'import MDAnalysis'`

Thank you for your answer.
if i run run `python -c 'import MDAnalysis'` in terminal, nothing is displayed. (i click 'send' and go in a new line)
I use Ubuntu, so i have Python 2.7.17 and Python 3.6.9.
in tutorial.sh i have modified the frist two lines accordingly to my installation.
So i used this command: 
python setup.py install --home=test
And i modified in this way:
export PYTHONPATH=$PYTHONPATH:/home/user/Scrivania/pietro/pyinteraph-master/test/lib/python/libinteract
export PYINTERAPH=/home/user/Scrivania/pietro/pyinteraph-master/test/pyinteraph
export PATH=$PATH:$PYINTERAPH. 
I tried to verify the MDAnalysis version, with this command: python -c 'import MDAnalysis as mda; print(mda.__version__)' and it is:  0.20.1

**Comment by degapifa** [comment]
i try to reinstall MDanlysis and now i have a new problem...
Traceback (most recent call last):
  File "/home/z4-19/Scrivania/pietro/pyinteraph-master/test/pyinteraph/pyinteraph", line 162, in <module>
    from libinteract import libinteract as li
  File "/home/z4-19/Scrivania/pietro/pyinteraph-master/test/lib/python/libinteract/libinteract.py", line 8, in <module>
    from innerloops import LoopDistances
ImportError: /home/z4-19/Scrivania/pietro/pyinteraph-master/test/lib/python/libinteract/innerloops.so: undefined symbol: sqmI

**Comment by mtiberti** [comment]
1) Notice PyInteraph needs MDAnalysis 0.7.6 which is a bit old and not super easy to install nowadays. We're working on a version that will run on the latest MDAnalysis and Python 3, that will certainly be easier to support 
2) About your second error, it's a bit strange - have you changed something else in your build system? I recommend you restart from scratch and re-building the libraries (by running setup.py)
